[general]
static=yes
writeprotect=no
clearglobalvars=no

[default]
exten => 8888,1,Answer()
 same => n,NoOp(Echo test)
 same => n,Echo()
 same => n,Hangup()

[from-novofon]
exten => _X.,1,NoOp(Inbound from Novofon: ${EXTEN})
 same => n,Goto(default,8888,1)

[from-livekit]
exten => _X.,1,NoOp(From LiveKit to PSTN: ${EXTEN})
 ; На время тестов подставим ваш E.164 номер в АОН
 same => n,Set(CALLERID(num)=79843330712)
 ; Набираем через Novofon c правильным Request-URI
 same => n,Dial(PJSIP/novofon-endpoint/sip:${EXTEN}@sip.novofon.ru:5060,60)
 same => n,Hangup()

[confirm-trunk]
exten => start,1,NoOp(Confirm Novofon SIP Trunk)
 same => n,Set(CALLERID(num)=79843330712)
 same => n,Dial(PJSIP/novofon-8888-endpoint,12)
 same => n,Hangup()
