services:
  - type: web
    name: audiobot
    env: python
    buildCommand: |
      # Install Python dependencies
      pip install --upgrade pip
      pip install -r requirements.txt
      
      # Install Node.js dependencies and build frontend
      cd frontend && yarn install && yarn build
    startCommand: uvicorn app.main:app --host=0.0.0.0 --port=$PORT
    envVars:
      - key: MONGO_URL
        value: mongodb+srv://vashdomkaluga_db_user:Vasdom40a@cluster0.lhqxfbi.mongodb.net/?retryWrites=true&w=majority&appName=ClusterD
      - key: DB_NAME  
        value: ClusterD
      - key: BITRIX24_WEBHOOK_URL
        value: https://vas-dom.bitrix24.ru/rest/1/4l8hq1gqgodjt7yo/
      - key: EMERGENT_LLM_KEY
        value: sk-emergent-0A408AfAeF26aCd5aB
      - key: BOT_TOKEN
        value: 7860360375:AAEVEQCbsqCnP-aHJOlqOCHaTwginuLNe0E
      - key: TELEGRAM_BOT_TOKEN
        value: 8327964029:AAHBMITlIY8ZWLn34mpg82d1-Cb-8RXTSmQ
      - key: TELEGRAM_WEBHOOK_URL
        value: https://audiobot-qci2.onrender.com/telegram/webhook
      - key: OPENROUTER_API_KEY
        value: sk-or-v1-d1f50246cd027109960ldfb432d72441ea00c99d49a96729a78125c61ac4dd
      - key: CORS_ORIGINS
        value: "*"