services:
  - type: web
    name: vasdom-backend
    env: python
    rootDir: .
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn backend.server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: BITRIX24_WEBHOOK_URL
        sync: false
      - key: EMERGENT_LLM_KEY
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: CORS_ORIGINS
        value: "*"

  - type: static
    name: vasdom-frontend
    rootDir: frontend
    buildCommand: yarn && yarn build
    publishPath: build
    envVars:
      - key: REACT_APP_BACKEND_URL
        value: https://audiobot-qci2.onrender.com
      - key: REACT_APP_FRONTEND_URL
        value: https://audiobot-1-cv3f.onrender.com
